Fixed a problem in method "_alias_method_chain_ensuring_inheritability(target, feature, &block)" which was causing following exception:
RuntimeError: implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

when running the tests with Ruby 2.1.2